### ISSUE TITLE
Link plis

### ISSUE THREAD

**Issue by miquelt9** [romeuesteve/romeuesteve.github.io#1]
Holap, fica el [link](https://romeuesteve.github.io/cronofib.html) de l'aplicació a la descripció (about section) x fer més fàcil l'accés a aquessta.
Also, bona feina :))) (passava sovint q volies utilitzar-ho quan estava tancat a la defib)

**Comment by miquelt9** [comment]
Btw si crees issues de coses que vols fer crec que puc intentar ajudar xd

**Comment by romeuesteve** [comment]
Merci! He actualitzat la web sencera fent-la de nou amb noves funcionalitats, com seleccionar els grups de cada assignatura que vols utilitzar, i ja está posat el link en la descripció, perdó per la tardança 😅, fins ara no m'havia motivat a continuar el projecte
