### ISSUE TITLE
No funciona con asignaturas con solo un grupo

### ISSUE THREAD

**Issue by theOfficeCat** [romeuesteve/romeuesteve.github.io#2]
En las asignaturas de un solo grupo no genera horarios. No he podido ejecutar localmente el código pero deduzco que el problema está en que en el JSON que devuelve la API no hay subgrupos y la función deeply considera que no es válido el horario cuando debería serlo.

Resultado actual de la web:
![image](https://github.com/romeuesteve/romeuesteve.github.io/assets/12856430/e6fcb342-3cb4-4887-88dc-f829b4b27852)

Aplicación de horarios oficial de la FIB:
![image](https://github.com/romeuesteve/romeuesteve.github.io/assets/12856430/566aa8a3-4cca-476a-967e-bc0b28719945)

JSON que devuelve la API con esa asignatura:
```JSON
{
    "comentaris": [],
    "count": 3,
    "results": [
        {
            "codi_assig": "XC2",
            "grup": "10",
            "dia_setmana": 1,
            "inici": "10:00",
            "durada": 2,
            "tipus": "L",
            "aules": "D6003",
            "idioma": "Català"
        },
        {
            "codi_assig": "XC2",
            "grup": "10",
            "dia_setmana": 4,
            "inici": "12:00",
            "durada": 2,
            "tipus": "T",
            "aules": "A6201",
            "idioma": "Castellano"
        },
        {
            "codi_assig": "XC2",
            "grup": "10",
            "dia_setmana": 5,
            "inici": "09:00",
            "durada": 1,
            "tipus": "T",
            "aules": "A6201",
            "idioma": "Castellano"
        }
    ]
}
```

**Comment by romeuesteve** [comment]
He actualizado la web con una nueva versión propia hecha desde cero, ya que algunas de las funciones que quería implementar hubieran requerido muchos cambios en el código original. Ahora ya está solucionado el bug y se pueden hacer horarios con todas las asignaturas, aparte de ahora poder seleccionar los grupos que quieres usar.

![ejemplo](https://github.com/romeuesteve/romeuesteve.github.io/assets/39237217/747ed702-be3d-4187-b54c-1a01430bbbaf)
Falta mejorar aspectos de la UI y optimizar cómo se extraen los datos de la API, pero al menos ahora es funcional para todos los casos y en muchos casos más eficiente.
