### ISSUE TITLE
Només funciona per al 2023Q2

### ISSUE THREAD

**Issue by Witixin1512** [romeuesteve/romeuesteve.github.io#3]
La pàgina web només retorna resultats per al 2023Q2, ja que totes les consultes a la api fan servir una url constant.

La forma correcte de fer consultes seria mitjançant una consulta previa a  `https://api.fib.upc.edu/v2/quadrimestres/actual-horaris/` i fer servir el resultat per a construir les noves urls.

Actualment la api retorna el següent:
```json
{
    "id": "2024Q1",
    "url": "https://api.fib.upc.edu/v2/quadrimestres/2024Q1/",
    "actual": "S",
    "actual_horaris": "S",
    "classes": "https://api.fib.upc.edu/v2/quadrimestres/2024Q1/classes/",
    "examens": "https://api.fib.upc.edu/v2/quadrimestres/2024Q1/examens/",
    "assignatures": "https://api.fib.upc.edu/v2/quadrimestres/2024Q1/assignatures/"
}
```

**Comment by EncryptEx** [comment]
Cert! 
Aqui tens una preview del fix: https://encryptex.github.io/cronofib/
